Repository CBNU-DBS/Touchless_PDF_Viewer-Client, pull requests merged in 2022-07, with the labels that each got.

#36 resovle #30 액티비티 화면 연결
  Client/.idea/deploymentTargetDropDown.xml
  Client/.idea/gradle.xml
  Client/.idea/misc.xml
  Client/app/src/main/AndroidManifest.xml
  Client/app/src/main/java/com/example/client/JoinActivity.java
  Client/app/src/main/java/com/example/client/LoginActivity.java
  Client/app/src/main/java/com/example/client/MypageActivity.java
  Client/app/src/main/java/com/example/client/Personal_info_setting_Activity.java
  Client/app/src/main/java/com/example/client/fragment/DocumentFragment.java
  Client/app/src/main/java/com/example/client/fragment/HomeFragment.java
  Client/app/src/main/java/com/example/client/fragment/SettingFragment.java
  Client/app/src/main/res/layout/activity_home.xml
  Client/app/src/main/res/layout/activity_join.xml
  Client/app/src/main/res/layout/activity_login.xml
  Client/app/src/main/res/layout/activity_mypage.xml
  Client/app/src/main/res/layout/activity_personal_info_setting.xml
Labels: ✨Feature

#41 Feature : 마이페이지 화면 오류 해결 및 구글 드라이브 기능 구현
  Client/.idea/misc.xml
  Client/app/src/main/java/com/example/client/MypageActivity.java
  Client/app/src/main/res/drawable-xxxhdpi/personal_profile.png
  Client/app/src/main/res/layout/activity_mypage.xml
Labels: 🔥BugFix, ✨Feature

#40 Refactor/#38
  Client/app/src/main/AndroidManifest.xml
  Client/app/src/main/java/com/example/client/PDF_View_Activity.java
  Client/app/src/main/java/com/example/client/java/CameraXLivePreviewActivity.java
  Client/app/src/main/java/com/example/client/java/CameraXSourceDemoActivity.java
  Client/app/src/main/java/com/example/client/java/LivePreviewActivity.java
  Client/app/src/main/java/com/example/client/java/StillImageActivity.java
  Client/app/src/main/java/com/example/client/java/barcodescanner/BarcodeGraphic.java
  Client/app/src/main/java/com/example/client/java/barcodescanner/BarcodeScannerProcessor.java
  Client/app/src/main/java/com/example/client/java/facedetector/FaceGraphic.java
  Client/app/src/main/java/com/example/client/java/labeldetector/LabelDetectorProcessor.java
  Client/app/src/main/java/com/example/client/java/labeldetector/LabelGraphic.java
  Client/app/src/main/java/com/example/client/java/objectdetector/ObjectDetectorProcessor.java
  Client/app/src/main/java/com/example/client/java/objectdetector/ObjectGraphic.java
  Client/app/src/main/java/com/example/client/java/posedetector/PoseDetectorProcessor.java
  Client/app/src/main/java/com/example/client/java/posedetector/PoseGraphic.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/ClassificationResult.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/EMASmoothing.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/PoseClassifier.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/PoseClassifierProcessor.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/PoseEmbedding.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/PoseSample.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/RepetitionCounter.java
  Client/app/src/main/java/com/example/client/java/posedetector/classification/Utils.java
  Client/app/src/main/java/com/example/client/java/segmenter/SegmentationGraphic.java
  Client/app/src/main/java/com/example/client/java/segmenter/SegmenterProcessor.java
  Client/app/src/main/java/com/example/client/java/textdetector/TextGraphic.java
  Client/app/src/main/java/com/example/client/java/textdetector/TextRecognitionProcessor.java
  Client/app/src/main/res/layout/activity_home.xml
  Client/app/src/main/res/layout/activity_login.xml
  Client/app/src/main/res/layout/activity_main.xml
Labels: 🔨Refactor

#45 테스트 PDF 사용하여 PDF_View 구현
  Client/.idea/misc.xml
  Client/app/src/main/AndroidManifest.xml
  Client/app/src/main/java/com/example/client/LoginActivity.java
  Client/app/src/main/java/com/example/client/PDF_View_Activity.java
  Client/app/src/main/java/com/example/client/java/facedetector/FaceGraphic.java
  Client/app/src/main/res/layout/activity_login.xml
Labels: ✨Feature

#43 Feature: 회원가입 API 연결
  Client/.idea/codeStyles/Project.xml
  Client/.idea/codeStyles/codeStyleConfig.xml
  Client/.idea/deploymentTargetDropDown.xml
  Client/.idea/misc.xml
  Client/app/build.gradle
  Client/app/src/main/AndroidManifest.xml
  Client/app/src/main/java/com/example/client/JoinActivity.java
  Client/app/src/main/java/com/example/client/RetrofitClient.java
  Client/app/src/main/java/com/example/client/api/UserApi.java
  Client/app/src/main/java/com/example/client/dto/ResponseDTO.java
  Client/app/src/main/java/com/example/client/dto/UserDTO.java
  Client/app/src/main/res/layout/activity_join.xml
  Client/app/src/main/res/xml/network_security_config.xml
Labels: ✨Feature

#49 구글드라이브 연동 오류 해결
  Client/.idea/deploymentTargetDropDown.xml
  Client/.idea/misc.xml
  Client/app/src/main/AndroidManifest.xml
  Client/app/src/main/java/com/example/client/MypageActivity.java
  Client/app/src/main/java/com/example/client/fragment/HomeFragment.java
Labels: 🔥BugFix
